### ISSUE TITLE
classic keeps redirecting me to new!

### ISSUE THREAD

**Issue by rshorey** [fecgov/FEC#4364]
If I want to look at a filing on classic, I usually follow this path:

* go to http://classic.fec.gov/finance/disclosure/candcmte_info.shtml
* search for the committee
* click on the filing

But when I'm done with that filing, I often want to explore that committee more or find another committee within classic. But when I click on anything in this breadcrumbs menu...

<img width="510" alt="screen shot 2017-07-15 at 6 54 28 pm" src="https://user-images.githubusercontent.com/901091/28243194-20da7fd0-698f-11e7-9f70-e91932243070.png">

...I get sent to the new site! since I can only get into classic by starting in classic, it seems like I should get to stay in classic!!!

Thanks.

**Comment by noahmanger** [comment]
Ah! Sorry about this. This is because we set up redirects for committee pages so that pre-existing links wouldn't break. But now I'm wondering if there's a better solution here. @patphongs is it possible to decide whether or not to redirect based on the referrer?

**Comment by patphongs** [comment]
@rshorey, thanks for flagging this. This is because the breadcrumbs on docquery.fec.gov are set to the www.fec.gov domain instead of classic.fec.gov. We would have to get the breadcrumbs updated in the docquery page template to point to the classic.fec.gov domain. We'll take a closer look at this with the team to see what we can do. cc @noahmanger

**Comment by noahmanger** [comment]
Ah thanks for clarifying!
