### ISSUE TITLE
Campaign Finance Data Search

### ISSUE THREAD

**Issue by Bcdeutsch** [fecgov/FEC#4668]
Is there an easier (with fewer clicks) way to get to the search function located on the left pane of https://www.fec.gov/data/filings/?data_type=processed?

**Comment by jwchumley** [comment]
The quickest way to navigate to it is three clicks from the home page:


Campaign finance data tab

Filings and reports

All filings


Because the URLs are permanent you can also save a link directly to that page.


Regards,


Jeff


Jeff Chumley

Electronic Filing, Web and Disclosure Branch Manager

Federal Election Commission



________________________________
