### ISSUE TITLE
Report and Data availability

### ISSUE THREAD

**Issue by jbucelato** [fecgov/FEC#7639]
Public Records has gotten an uptick in calls about historical reports and the associated data not being available online, even though it "appears" to be online.
Could it be possible to put a blurb about availability, like there was on the old site:
![capture](https://user-images.githubusercontent.com/26546554/43458311-d4db872a-9497-11e8-830a-e2f3efcb64ba.JPG)

Jason
Public Records

**Comment by PaulClark2** [comment]
I agree we should include this language on pages that allow users view older data. They need to understand why they can't view the images of reports. 

The language Jason posted above is on this page, https://classic.fec.gov/finance/disclosure/help_candidate_committee_viewer.shtml near the bottom. 

We currently scan all paper reports received at the Federal Election Commission. This includes reports filed by campaigns for the House of Representatives and for President, along with reports by political party committees and political action committees who participate in Federal elections. Scanned images of reports filed with the Secretary of the Senate are included here as well.

Older paper reports are available with the following limitations.

PAC, party and presidential filings since 1993
House committee filings since May 1996
Senate filings since May 2000

**Comment by AmyKort** [comment]
Where on the new site would we want that language to go?

**Comment by jbucelato** [comment]
Perhaps a pop-up on Filings:
![capture](https://user-images.githubusercontent.com/26546554/43460796-aecd1596-949f-11e8-9511-6530a01c5f63.JPG)

or in the empty space here:
![capture](https://user-images.githubusercontent.com/26546554/43460907-022e2e5a-94a0-11e8-8c64-f0ec2f682c13.JPG)
