### ISSUE TITLE
Filters not working.

### ISSUE THREAD

**Issue by jbucelato** [fecgov/FEC#9498]
There is a candidate missing from the list, Tonya Millis, https://www.fec.gov/data/candidates/?party=LIB&name=IN&is_active_candidate=true. Also, I selected a specific state and I getting candidates from other states,
The candidate does appear correctly here, https://www.fec.gov/data/candidates/house/?election_year=2020&election_full=True&party=LIB&name=IN&is_active_candidate=true, however, candidates from other states appear as well.

Thanks for looking into this.

Jason

**Comment by PaulClark2** [comment]
The state filter seems to be applying a name filter instead of a state filter: https://www.fec.gov/data/candidates/?name=IN 

![image](https://user-images.githubusercontent.com/11817734/73566708-82b25400-4432-11ea-96b6-454f15844948.png)

The state filter seems to be applying a name filter instead of a state filter:
https://www.fec.gov/data/candidates/house/?election_year=2020&election_full=True&party=LIB&name=IN&is_active_candidate=true

![image](https://user-images.githubusercontent.com/11817734/73567007-6531ba00-4433-11ea-9a6a-7ad5da179ec0.png)

**Comment by PaulClark2** [comment]
Issue moved to [fecgov/fec-cms #3512](https://github.com/fecgov/fec-cms/issues/3512) via [**ZenHub**](https://www.zenhub.com/)
